### ISSUE TITLE
Use symfony/panther 1.0.*

### ISSUE THREAD

**Issue by webignition** [webignition/basil-worker#789]
- [x] webignition/base-basil-test-case#115
- [x] webignition/symfony-panther-webserver-runner#11
- [x] webignition/symfony-panther-dom-crawler-navigator#71
- [x] webignition/base-panther-test-case#29
- [x] webignition/php-basil-compilable-source-factory#581
- [x] webignition/basil-phpunit-result-printer#130
- [x] webignition/basil-cli-compiler#247
- [x] webignition/basil-cli-runner#172
- [x] webignition/basil-worker-web#65
- [x] webignition/basil-worker-handler#52
